name: prova_agenda
description: "A new Flutter project."

publish_to: 'none' # Não publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Atualiza de acordo com a versão do Dart SDK

dependencies:
  flutter:
    sdk: flutter

  # Dependência para gerenciamento de ícones estilo iOS
  cupertino_icons: ^1.0.8

  # Dependência para armazenar dados localmente no dispositivo
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Boas práticas de lint para o Flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
